// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2tXoMTVz198Og_BGdfKGX_nU3yz3ZHoU',
    appId: '1:183124088625:android:fab434f373a783dfe00210',
    messagingSenderId: '183124088625',
    projectId: 'e-vision-panama-app',
    databaseURL: 'https://e-vision-panama-app.firebaseio.com',
    storageBucket: 'e-vision-panama-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvwgD_re8Rnky2kRaX7O-GCnVS4Gbp4U',
    appId: '1:183124088625:ios:6c80c1853fdfe301e00210',
    messagingSenderId: '183124088625',
    projectId: 'e-vision-panama-app',
    databaseURL: 'https://e-vision-panama-app.firebaseio.com',
    storageBucket: 'e-vision-panama-app.appspot.com',
    androidClientId: '183124088625-3117bvufhn0btg7q5sepfqccjpq6g9li.apps.googleusercontent.com',
    iosClientId: '183124088625-k0giv7v21nuv7pvlkptaj5qvgi3goi02.apps.googleusercontent.com',
    iosBundleId: 'com.evision.iOS',
  );
}
